### ISSUE TITLE
Custom elements are matched cumulatively across multiple destinations

### ISSUE THREAD

**Issue by schmod** [jsolis/grunt-ngie#2]
If I configure grunt-ngie to output to multiple destinations, I all destinations include the custom elements found for any previous destination:

For example:
```js
{
    dist: {
        files: {
            'deploy/index.html': ['dist/scripts/main/*.js'],
            'deploy/404.html': ['dist/scripts/404/*.js']
        }
    }
}
```

`index.html` is processed correctly, but `404.html` includes all of the custom elements found in `dist/scripts/main/*.js` *in addition* to the custom elements that I actually asked for.

**Comment by jsolis** [comment]
This is an excellent point. Before I close this, I just want to confirm that the big pull request that I merged in addresses this issue.
